import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { PrismaService } from "../../database/prisma.service.js";
import type { Prisma } from "../../generated/prisma/client.js";
import type { CreateCategory, CreateLocation, CreateService, Pagination, ReplaceBusinessHours, UpdateCategory, UpdateLocation, UpdateService } from "./catalog.schemas.js";

const pageResult = <T>(items: T[], total: number, page: number, pageSize: number) => ({ items, pagination: { page, pageSize, total, pages: Math.ceil(total / pageSize) } });
const timeAtUtc = (value: string): Date => new Date(`1970-01-01T${value}:00.000Z`);
const defined = <T extends object>(value: T): { [K in keyof T]?: Exclude<T[K], undefined> } => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as { [K in keyof T]?: Exclude<T[K], undefined> };

@Injectable()
export class CatalogService {
  constructor(private readonly prisma: PrismaService) {}
  listCategories(tenantId: string, query: Pagination) { return this.prisma.withTenant(tenantId, async (tx) => { const where = { tenantId, ...(query.active === undefined ? {} : { isActive: query.active }), ...(query.search ? { name: { contains: query.search, mode: "insensitive" as const } } : {}) }; const [items, total] = await Promise.all([tx.serviceCategory.findMany({ where, orderBy: [{ sortOrder: "asc" }, { name: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), tx.serviceCategory.count({ where })]); return pageResult(items, total, query.page, query.pageSize); }); }
  createCategory(tenantId: string, data: CreateCategory) { return this.prisma.withTenant(tenantId, (tx) => tx.serviceCategory.create({ data: { ...defined(data), tenantId } as Prisma.ServiceCategoryUncheckedCreateInput })); }
  updateCategory(tenantId: string, id: string, data: UpdateCategory) { return this.prisma.withTenant(tenantId, async (tx) => { const existing = await tx.serviceCategory.findFirst({ where: { id, tenantId }, select: { id: true } }); if (!existing) throw new NotFoundException("Service category was not found"); return tx.serviceCategory.update({ where: { id }, data: defined(data) }); }); }
  deleteCategory(tenantId: string, id: string) { return this.prisma.withTenant(tenantId, async (tx) => { const existing = await tx.serviceCategory.findFirst({ where: { id, tenantId }, include: { _count: { select: { services: true } } } }); if (!existing) throw new NotFoundException("Service category was not found"); if (existing._count.services > 0) throw new UnprocessableEntityException("A category with services cannot be deleted"); await tx.serviceCategory.delete({ where: { id } }); }); }

  listServices(tenantId: string, query: Pagination) { return this.prisma.withTenant(tenantId, async (tx) => { const where = { tenantId, ...(query.active === undefined ? {} : { isActive: query.active }), ...(query.search ? { name: { contains: query.search, mode: "insensitive" as const } } : {}) }; const [items, total] = await Promise.all([tx.service.findMany({ where, include: { category: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), tx.service.count({ where })]); return pageResult(items, total, query.page, query.pageSize); }); }
  createService(tenantId: string, data: CreateService) { return this.prisma.withTenant(tenantId, async (tx) => { const category = await tx.serviceCategory.findFirst({ where: { id: data.categoryId, tenantId }, select: { id: true } }); if (!category) throw new UnprocessableEntityException("The selected category does not belong to this tenant"); return tx.service.create({ data: { ...defined(data), tenantId } as Prisma.ServiceUncheckedCreateInput }); }); }
  updateService(tenantId: string, id: string, data: UpdateService) { return this.prisma.withTenant(tenantId, async (tx) => { const existing = await tx.service.findFirst({ where: { id, tenantId }, select: { id: true } }); if (!existing) throw new NotFoundException("Service was not found"); if (data.categoryId && !(await tx.serviceCategory.findFirst({ where: { id: data.categoryId, tenantId }, select: { id: true } }))) throw new UnprocessableEntityException("The selected category does not belong to this tenant"); return tx.service.update({ where: { id }, data: defined(data) }); }); }
  archiveService(tenantId: string, id: string) { return this.updateService(tenantId, id, { isActive: false }); }

  listLocations(tenantId: string, query: Pagination) { return this.prisma.withTenant(tenantId, async (tx) => { const where = { tenantId, ...(query.active === undefined ? {} : { isActive: query.active }), ...(query.search ? { name: { contains: query.search, mode: "insensitive" as const } } : {}) }; const [items, total] = await Promise.all([tx.location.findMany({ where, include: { businessHours: { orderBy: { dayOfWeek: "asc" } } }, orderBy: [{ isMain: "desc" }, { name: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), tx.location.count({ where })]); return pageResult(items, total, query.page, query.pageSize); }); }
  createLocation(tenantId: string, data: CreateLocation) { return this.prisma.withTenant(tenantId, async (tx) => { if (data.isMain) await tx.location.updateMany({ where: { tenantId, isMain: true }, data: { isMain: false } }); return tx.location.create({ data: { ...defined(data), tenantId } as Prisma.LocationUncheckedCreateInput }); }); }
  updateLocation(tenantId: string, id: string, data: UpdateLocation) { return this.prisma.withTenant(tenantId, async (tx) => { const existing = await tx.location.findFirst({ where: { id, tenantId }, select: { id: true } }); if (!existing) throw new NotFoundException("Location was not found"); if (data.isMain) await tx.location.updateMany({ where: { tenantId, isMain: true, NOT: { id } }, data: { isMain: false } }); return tx.location.update({ where: { id }, data: defined(data) }); }); }
  archiveLocation(tenantId: string, id: string) { return this.updateLocation(tenantId, id, { isActive: false, isMain: false }); }
  replaceBusinessHours(tenantId: string, locationId: string, data: ReplaceBusinessHours) { return this.prisma.withTenant(tenantId, async (tx) => { if (!(await tx.location.findFirst({ where: { id: locationId, tenantId }, select: { id: true } }))) throw new NotFoundException("Location was not found"); await tx.businessHour.deleteMany({ where: { tenantId, locationId } }); if (data.hours.length) await tx.businessHour.createMany({ data: data.hours.map((hour) => ({ tenantId, locationId, dayOfWeek: hour.dayOfWeek, isClosed: hour.isClosed, openTime: hour.isClosed || !hour.openTime ? null : timeAtUtc(hour.openTime), closeTime: hour.isClosed || !hour.closeTime ? null : timeAtUtc(hour.closeTime) })) }); return tx.businessHour.findMany({ where: { tenantId, locationId }, orderBy: { dayOfWeek: "asc" } }); }); }
}
