import { Injectable } from "@nestjs/common"; import { PrismaService } from "../../database/prisma.service.js"; import type { z } from "zod"; import type { rangeSchema } from "./reports.schemas.js";
type Range=z.infer<typeof rangeSchema>;
@Injectable() export class ReportsService { constructor(private readonly prisma:PrismaService){}
 dashboard(tenantId:string){return this.prisma.withTenant(tenantId,async tx=>{const now=new Date(),end=new Date(now.getTime()+86400000); const [bookings,customers,services,locations]=await Promise.all([tx.booking.count({where:{tenantId,startAt:{gte:now,lt:end}}}),tx.customer.count({where:{tenantId,anonymizedAt:null}}),tx.service.count({where:{tenantId,isActive:true}}),tx.location.count({where:{tenantId,isActive:true}})]);return{asOf:now,bookingsToday:bookings,customers,activeServices:services,activeLocations:locations};});}
 agenda(tenantId:string,r:Range){return this.prisma.withTenant(tenantId,tx=>tx.booking.findMany({where:{tenantId,startAt:{gte:r.from,lte:r.to}},include:{customer:true,service:true,location:true},orderBy:{startAt:"asc"},skip:(r.page-1)*r.pageSize,take:r.pageSize}));}
 detail(tenantId:string,r:Range){return this.prisma.withTenant(tenantId,async tx=>{const where={tenantId,createdAt:{gte:r.from,lte:r.to}};const [items,total]=await Promise.all([tx.booking.findMany({where,include:{customer:true,service:true,location:true},orderBy:{createdAt:"desc"},skip:(r.page-1)*r.pageSize,take:r.pageSize}),tx.booking.count({where})]);return{items,pagination:{page:r.page,pageSize:r.pageSize,total,pages:Math.ceil(total/r.pageSize)}};});}
 demand(tenantId:string,r:Range){return this.prisma.withTenant(tenantId,tx=>tx.booking.groupBy({by:["serviceId","serviceName"],where:{tenantId,startAt:{gte:r.from,lte:r.to}},_count:{_all:true},_sum:{servicePrice:true},orderBy:{_count:{serviceId:"desc"}}}));}
 availability(tenantId:string){return this.prisma.withTenant(tenantId,async tx=>{const [locations,hours]=await Promise.all([tx.location.findMany({where:{tenantId,isActive:true},select:{id:true,name:true}}),tx.businessHour.findMany({where:{tenantId},orderBy:[{locationId:"asc"},{dayOfWeek:"asc"}]})]);return{locations:locations.map(l=>({...l,hours:hours.filter(h=>h.locationId===l.id)}))};});}
}
